address/urls.py
from django.urls import path, include
from .views import CheckoutView

app_name = 'address'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

blog/urls.py
from django.urls import path, include

app_name = 'blog'


urlpatterns = [

]

coupon/urls.py
from django.urls import path, include
from .views import AddCouponView
app_name = 'coupon'

urlpatterns = [
    path('coupon/', AddCouponView.as_view(), name="add_coupon"),
]

orders/urls.py
from django.urls import path, include
from .views import OrderView, add_to_cart, remove_from_cart, remove_single_item_from_cart
app_name = 'orders'

urlpatterns = [
    path('order-summary/', OrderView.as_view(), name='order_summary'),

    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),

    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),

    path('remove-item-from-cart/<slug>/',
         remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

payments/urls.py
from django.urls import path, include
from .views import PaymentView

app_name = 'payments'


urlpatterns = [
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('address.urls', namespace='address')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('contactus.urls', namespace='contactus')),
    path('', include('coupon.urls', namespace='coupon')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('payments.urls', namespace='payments')),
    path('', include('products.urls', namespace='products')),
    path('', include('refound.urls', namespace='refounds')),
    path('', include('search.urls', namespace='search')),

    # path('__debug__/', include(debug_toolbar.urls)),


]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path, include
from .views import SearchItemView
app_name = 'search'

urlpatterns = [
    path('search/products/', SearchItemView.as_view(), name='search_products'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    # title
    pass

payments/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Start model Payment


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

# End Model Payment

payments/forms.py
from django import forms


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

blog/views.py
from django.shortcuts import render

# Create your views here.

payments/views.py
from orders.views import create_ref_code
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Payment
from django.views.generic import View, ListView, DetailView
from address.forms import CheckoutForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from orders.models import Order, OrderItem
from accounts.models import UserProfile
from .forms import PaymentForm
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your views here.


class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'DISPLAY_COUPON_FORM': False
            }

            userprofile = self.request.user.userprofile
            if userprofile.one_click_purchasing:
                # fetch the users card list
                cards = stripe.Customer.list_sources(
                    userprofile.stripe_customer_id,
                    limit=3,
                    object='card'
                )
                card_list = cards['data']
                if len(card_list) > 0:
                    context.update({
                        'card': card_list[0]
                    })
            return render(self.request, 'payment.html', context)
        else:
            messages.warning(
                self.request, "You have not added a billing address")
            return redirect("address:checkout")

    def post(self, *args, **Kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        form = PaymentForm(self.request.POST)
        userprofile = UserProfile.objects.get(user=self.request.user)
        if form.is_valid():
            token = form.cleaned_data.get('stripeToken')
            save = form.cleaned_data.get('save')
            use_default = form.cleaned_data.get('use_default')

            if save:
                if userprofile.stripe_customer_id != '' and userprofile.stripe_customer_id is not None:
                    customer = stripe.Customer.retrieve(
                        userprofile.stripe_customer_id)
                    customer.sources.create(source=token)

                else:
                    customer = stripe.Customer.create(
                        email=self.request.user.email,
                    )
                    customer.sources.create(source=token)
                    userprofile.stripe_customer_id = customer['id']
                    userprofile.one_click_purchasing = True
                    userprofile.save()
            amount = int(order.get_total() * 100)  # cents
            token = self.request.POST.get('stripeToken')

            try:
                if use_default or save:
                    # charge the customer because we cannot charge the token more than once
                    charge = stripe.Charge.create(
                        amount=amount,  # cents
                        currency="usd",
                        customer=userprofile.stripe_customer_id
                    )
                else:
                    # Use Stripe's library to make requests...
                    charge = stripe.Charge.create(
                        amount=amount,
                        currency="usd",
                        source=token
                    )

                # Create the Payment
                payment = Payment()
                payment.stripe_charge_id = charge['id']
                payment.user = self.request.user
                payment.amount = order.get_total()
                payment.save()

                # assign the payment to the order
                order_item = OrderItem.objects.all()
                order_item.update(ordered=True)
                for item in order_item:
                    item.save()

                order.ordered = True
                order.payment = payment
                order.ref_code = create_ref_code()
                order.save()

                messages.success(self.request, 'Your order was successful!')
                return redirect('orders:order_confirmation')

            except stripe.error.CardError as e:
                # Since it's a decline, stripe.error.CardError will be caught
                body = e.json_body
                err = body.get('error', {})
                messages.error(self.request, f"{err.get('message')}")
                return redirect('/')

            except stripe.error.RateLimitError as e:
                # Too many requests made to the API too quickly
                messages.error(self.request, 'Rate limit error')
                return redirect('/')

            except stripe.error.InvalidRequestError as e:
                # Invalid parameters were supplied to Stripe's API
                messages.error(self.request, 'Invalid prameters')
                return redirect('/')

            except stripe.error.AuthenticationError as e:
                # Authentication with Stripe's API failed
                # (maybe you changed API keys recently)
                messages.error(self.request, 'Not authenticated')
                return redirect('/')

            except stripe.error.APIConnectionError as e:
                # Network communication with Stripe failed
                messages.error(self.request, 'Network error')
                return redirect('/')

            except stripe.error.StripeError as e:
                # Display a very generic error to the user, and maybe send
                # yourself an email
                messages.error(
                    self.request, 'Something went wrong. You were not charged. Please try again.')
                return redirect('/')

            except Exception as e:
                # Send an email to ourselves
                messages.error(
                    self.request, 'A serious error occurred. We have been notifed.')
                return redirect('/')

templates/base.html
{% load cart_template_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Furniture Store</title>
	{% block extra_head %}
	{% endblock %}

  <!-- Bootstrap core CSS -->
  {% comment %} <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> {% endcomment %}
  <!-- Material Design Bootstrap -->
  {% comment %} <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet"> {% endcomment %}
  <!-- Your custom styles (optional) -->
  {% comment %} <link href="{% static 'css/style.min.css' %}" rel="stylesheet"> {% endcomment %}


	<link rel="icon" href="{% static 'img/Fevicon.png' %}" type="image/png">
	<link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/nice-select/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@900&display=swap" rel="stylesheet">

</head>

<body>
	<!--================ Start Header Menu Area =================-->
	<header class="header_area">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light">
				<div class="container">
					<a class="navbar-brand logo_h" href="{% url 'products:home' %}"><img
							src="{% static 'img/logo.png' %}" alt="">
						<p style="display: inline" className="stylefonting">Furniture Store</p>
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse"
						data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto mr-auto">
							<li class="nav-item active"><a class="nav-link" href="{% url 'products:home' %}">Home</a>
							</li>
							<li class="nav-item submenu dropdown">
								<a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
									aria-haspopup="true" aria-expanded="false">Shop</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link"
											href="{% url 'products:product_list_category' %}">Shop by Categories</a>
									</li>
									<li class="nav-item"><a class="nav-link"
											href="{% url 'products:product_list_brand' %}">
											Shop by Brands</a>
									</li>
								</ul>
							</li>

							<li class="nav-item submenu dropdown">

								{% if user.is_authenticated %}
								<a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
									aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>

								<ul class="dropdown-menu">
									{% if user.is_staff %}
									<li class="nav-item"><a class="nav-link" href="/admin">Admin Dashbord</a></li>
									{% endif %}
									<li class="nav-item"><a class="nav-link" href="{% url 'password_change' %}">Password change</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
								</ul>


								{% else %}
								<a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
									aria-haspopup="true" aria-expanded="false">Registration</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
								</ul>
								{% endif %}
							</li>

							<li class="nav-item"><a class="nav-link" href="{% url 'contactus:contactus' %}">Contact</a>
							</li>


							<ul class="nav-shop">
								<li class="nav-item">
									<!-- Search form -->
									<form method='GET' action='{% url "search:search_products" %}' class="form-inline d-flex justify-content-center md-form form-sm active-cyan-2 mt-2">
									<input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search"
										aria-label="Search" name='q' value='{{ request.GET.q }}'>
										<button class="nav-item" type="submit">
											<i class="fas fa-search" aria-hidden="true"></i>
										</button>
									</form>
								</li>

								{% if request.user.is_authenticated %}
								<li class="nav-item">
									<a href="{% url 'orders:order_summary' %}" class="nav-link waves-effect">
										<span class="badge red z-depth-1 mr-1"
											style="background-color: rgb(0, 47, 148);border-radius: 35%;color: azure;">
											{{ request.user|cart_item_count }} </span>
										<i class="fas fa-shopping-cart"></i>
										<span class="clearfix d-none d-sm-inline-block"> Cart </span>
									</a>
								</li>
								{% else %}
								<li class="nav-item">
									<main class="nav-link waves-effect">
										<i class="fas fa-shopping-cart"></i>
										<span class="clearfix d-none d-sm-inline-block"> Cart </span>
									</main>
								</li>

								{% endif %}

							</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
	</header>
	<!--================ End Header Menu Area =================-->



	<div class="mt-5 pt-4">
		{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endfor %}
		{% endif %}
	</div>

	{% block content %}
	{% endblock content %}

	{% block extra_body %}
	{% endblock %}







	<!--================ Start footer Area  =================-->
	<footer class="footer">
		<div class="footer-area">
			<div class="container">
				<div class="row section_gap">
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title large_title">Our Mission</h4>
							<p>
								So seed seed green that winged cattle in. Gathering thing made fly you're no
								divided deep moved us lan Gathering thing us land years living.
							</p>
							<p>
								So seed seed green that winged cattle in. Gathering thing made fly you're no divided
								deep moved
							</p>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Quick Links</h4>
							<ul class="list">
								<li><a href="{% url 'products:home' %}">Home</a></li>
								<li><a href="{% url 'products:product_list_category' %}">Shop</a></li>
								<li><a href="blog.html">Blog</a></li>
								{% if user.is_authenticated %}
								<li><a href="accounts/logout">Logout</a></li>
								{% else %}
								<li><a href="accounts/login">Login</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Created By</h4>
							<ul class="list" style="color: #fff">
								<li>Obour Institutes</li>
								<li>Mis-8 Team</li>
							</ul>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Contact Us</h4>
							<div class="ml-40">
								<p class="sm-head">
									<span class="fa fa-location-arrow"></span>
									Head Office
								</p>
								<p>(((Belbies)))</p>

								<p class="sm-head">
									<span class="fa fa-phone"></span>
									Phone Number
								</p>
								<p>
									+2011-xx-xx14 <br>
									+2012-xx-xx68
								</p>

								<p class="sm-head">
									<span class="fa fa-envelope"></span>
									Email
								</p>
								<p>
									Furniture‎‏-Store@mis.com <br>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">

						Copyright &copy;
						<script>document.write(new Date().getFullYear());</script> All rights reserved | This template
						is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="#" target="_blank">
							Furniture‎‏ Store MIS8</a>
					</p>
				</div>
			</div>
		</div>
	</footer>




	<!--================ End footer Area  =================-->
	<script src="{% static 'vendors/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendors/skrollr.min.js' %}"></script>
	<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
	<!-- <script src="{% static 'vendors/nice-select/jquery.nice-select.min.js' %}"></script> -->
	<script src="{% static 'vendors/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script> -->


	{% block extra_scripts %}
	{% endblock extra_scripts %}
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}


	<!-- ================ start banner area ================= -->
	<section class="blog-banner-area" id="contact">
		<div class="container h-100">
			<div class="blog-banner">
				<div class="text-center">
					<h1>Contact Us</h1>
					<nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
            </ol>
          </nav>
				</div>
			</div>
    </div>
	</section>
	<!-- ================ end banner area ================= -->

	<!-- ================ contact section start ================= -->
  <section class="section-margin--small">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <div id="map" style="height: 420px"></div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13782.101043204593!2d31.473375!3d30.279105!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x41b5ccabb7c832c2!2z2YXYudmH2K8g2KfZhNi52KjZiNixINin2YTYudin2YTZiQ!5e0!3m2!1sar!2seg!4v1585772788403!5m2!1sar!2seg" width="100%" height='650' frameborder="0" style="border:0" allowfullscreen="" aria-hidden="false" tabindex="0" title="myFramelocation"></iframe>
      </div>


      <div class="row">
      {% for con in contactus_info %}
      
        <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3> Head Office</h3>
              <p>{{  con.head_office }}</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-headphone"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">{{  con.mobil }}</a></h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="Furniture‎‏-Store@mis.com">{{  con.email }}</a></h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
              {% endfor %}
        <div class="col-md-8 col-lg-9">
          <form action="." class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
            {% csrf_token %}
            <div class="row">
              <div class="col-lg-5">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" placeholder="Enter your name">
                </div>
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" placeholder="Enter email address">
                </div>
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" placeholder="Enter Subject">
                </div>
              </div>
              <div class="col-lg-7">
                <div class="form-group">
                    <textarea class="form-control different-control w-100" name="message" id="message" cols="30" rows="5" placeholder="Enter Message"></textarea>
                </div>
              </div>
            </div>
            <div class="form-group text-center text-md-right mt-3">
              <button type="submit" class="button button--active button-contactForm">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ contact section end ================= -->
  
  {% endblock content %}

templates/order_summary.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- ================ start banner area ================= -->
<section class="blog-banner-area" id="blog">
    <div class="container h-100">
        <div class="blog-banner">
            <div class="text-center">
                <h1>Order Details</h1>
                <nav aria-label="breadcrumb" class="banner-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Order Summary
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- ================ end banner area ================= -->



<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Delete from Cart</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order_item in order.items.all %}
                        <tr>
                            <td>
                                <div>{{ forloop.counter }}</div>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="{{ order_item.item.get_absolute_url }}">
                                        <div class="d-flex">
                                            <img src="{% static 'img/product/three3.jpg' %}" alt="{{ order_item.item.title }}"
                                                style="height: 100px; width: 100px;">
                                        </div>
                                        <div class="media-body">
                                            <p>{{ order_item.item.title }}</p>
                                        </div>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <h5>{{ order_item.item.price }} LE</h5>
                            </td>
                            <td style="width: 10%;">
                                <a href="{% url 'orders:remove_single_item_from_cart' order_item.item.slug %}">
                                    <i class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'orders:add_to_cart' order_item.item.slug %}">
                                    <i class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>
                                <h5>{{ order_item.get_total_item_price }} LE</h5>
                            </td>
                            <td>
                                <a style='color: red;' href="{% url 'orders:remove_from_cart' order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan='5'>Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-primary float-right'
                                    href="{% url 'products:product_list_category' %}">Continue shopping</a>
                            </td>
                        </tr>


                        {% endfor %}

                        {% if order.get_total %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td><b>${{ order.get_total }}</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-warning float-right ml-2' href='{% url "address:checkout" %}'>Proceed
                                    to
                                    checkout</a>
                                <a class='btn btn-primary float-left'
                                    href='{% url "products:product_list_category" %}'>Continue shopping</a>
                            </td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->

{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

<!-- ================ start banner area ================= -->
<section class="blog-banner-area" id="blog">
  <div class="container h-100">
    <div class="blog-banner">
      <div class="text-center">
        <h1>Product Details</h1>
        <nav aria-label="breadcrumb" class="banner-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">
              {{ item.title }}
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- ================ end banner area ================= -->

<!--================Single Product Area =================-->
<div class="product_image_area">
  <div class="container">
    <div class="row s_product_inner">
      <div class="col-lg-6">
        <div
          class="owl-carousel owl-theme s_Product_carousel"
          style="display: block;"
        >
          <div class="single-prd-item">
            {% if item.image %}
            <img
              class="img-fluid"
              src="{% static 'img/product/three3.jpg' %}"
              alt="{{ item.title }}"
              style="height: 500px;"
            />
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <div class="s_product_text">
          <h3>{{ item.title }}</h3>
          <h2>{{ item.price }} LE</h2>
          <ul class="list">
            <li>
              <a class="active" href="{{ item.category.get_absolute_url }}"
                ><span>Category</span>:{{ item.category }}</a
              >
            </li>
            <li>
              <a class="active" href="{{ item.brand.get_absolute_url }}"
                ><span>Brand</span>:{{ item.brand }}</a
              >
            </li>
          </ul>
          <p>
            {{ item.description }}
          </p>
          <div class="product_count">
            <a class="btn btn-danger" href="{{ item.get_remove_from_cart_url }}"
              >Remove from Cart<i class="fas fa-shopping-cart"></i
            ></a>
            <a class="btn btn-primary" href="{{ item.get_add_to_cart_url }}"
              >Add to Cart<i class="fas fa-cart-plus"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--================End Single Product Area =================-->
{% endblock content %}